### ISSUE TITLE
Unexpectedly passing tests on CUDA

### ISSUE THREAD

**Issue by alexbatashev** [intel/llvm-test-suite#511]
The following two tests unexpectedly pass on CUDA (maybe on HIP):
```
SYCL :: DeprecatedFeatures/basic-program.cpp
SYCL :: DeprecatedFeatures/kernel-and-program.cpp
```

The only thing, that has changed about these tests is that they were moved from another directory. I also don't see any commits to intel/llvm, that could have caused such a failure (or, better say, success).

**Comment by AidanBeltonS** [comment]
The unexpected passing was introduced from intel/llvm PR https://github.com/intel/llvm/pull/4599. 
The issue was that CUDA was using a regex to search for kernels within the programs binary. Unfortunately, the regex search was not very reliable so in some cases `has_kernel` was not able to find kernels. The search has been replaced with `cuModuleGetFunction`, which is more reliable. 
So these tests are now passing along with module splitting tests for CUDA.

#469 has been merged, so you hopefully will not be having the unexpected pass message any more.

Unfortunately, `basic-program.cpp` and `kernel-and-program.cpp` are not yet passing on HIP.
